# Generated by Django 3.1.3 on 2020-12-23 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20201223_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='url_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 20, 31, 59, 203929, tzinfo=utc)),
        ),
    ]
